//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.ProcessKiller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.ProcessKiller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill a process..
        /// </summary>
        internal static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill all instances of &quot;{0}&quot;.
        /// </summary>
        internal static string plugin_kill_all {
            get {
                return ResourceManager.GetString("plugin_kill_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill {0} processes.
        /// </summary>
        internal static string plugin_kill_all_count {
            get {
                return ResourceManager.GetString("plugin_kill_all_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill all instances.
        /// </summary>
        internal static string plugin_kill_instances {
            get {
                return ResourceManager.GetString("plugin_kill_instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Killer.
        /// </summary>
        internal static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimun matches to show &quot;Kill all instances&quot;.
        /// </summary>
        internal static string plugin_setting_kill_all_count {
            get {
                return ResourceManager.GetString("plugin_setting_kill_all_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show command line of the process in the tool tip.
        /// </summary>
        internal static string plugin_setting_show_command_line {
            get {
                return ResourceManager.GetString("plugin_setting_show_command_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may slow down the plugin..
        /// </summary>
        internal static string plugin_setting_show_command_line_description {
            get {
                return ResourceManager.GetString("plugin_setting_show_command_line_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line.
        /// </summary>
        internal static string plugin_tool_tip_command_line {
            get {
                return ResourceManager.GetString("plugin_tool_tip_command_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Window.
        /// </summary>
        internal static string plugin_tool_tip_main_window {
            get {
                return ResourceManager.GetString("plugin_tool_tip_main_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Usage.
        /// </summary>
        internal static string plugin_tool_tip_memory {
            get {
                return ResourceManager.GetString("plugin_tool_tip_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string plugin_tool_tip_path {
            get {
                return ResourceManager.GetString("plugin_tool_tip_path", resourceCulture);
            }
        }
    }
}
