<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <useWPF>true</useWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyName>Community.PowerToys.Run.Plugin.ProcessKiller</AssemblyName>
        <RootNamespace>Community.PowerToys.Run.Plugin.ProcessKiller</RootNamespace>
        <PluginJson>$([System.IO.File]::ReadAllText('$(MSBuildProjectDirectory)/plugin.json'))</PluginJson>
        <Version>$([System.Text.RegularExpressions.Regex]::Match($(PluginJson), '"Version": "(\S+)"').Groups[1].Value)</Version>
        <Platforms>x64;ARM64</Platforms>
        <Title>Powertoys Run ProcessKiller</Title>
        <Product>Powertoys Run ProcessKiller Plugin</Product>
        <Authors>8LWXpg</Authors>
        <RepositoryUrl>https://github.com/8LWXpg/PowerToysRun-ProcessKiller</RepositoryUrl>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <DebugSymbols>true</DebugSymbols>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DefineConstants>TRACE</DefineConstants>
        <Optimize>true</Optimize>
        <DebugType>pdbonly</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="PowerToys.Common.UI">
            <HintPath>.\Lib\PowerToys.Common.UI.dll</HintPath>
        </Reference>
        <Reference Include="PowerToys.ManagedCommon">
            <HintPath>.\Lib\PowerToys.ManagedCommon.dll</HintPath>
        </Reference>
        <Reference Include="PowerToys.Settings.UI.Lib">
            <HintPath>.\Lib\PowerToys.Settings.UI.Lib.dll</HintPath>
        </Reference>
        <Reference Include="Wox.Infrastructure">
            <HintPath>.\Lib\Wox.Infrastructure.dll</HintPath>
        </Reference>
        <Reference Include="Wox.Plugin">
            <HintPath>.\Lib\Wox.Plugin.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <None Include="plugin.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.269">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="System.Management" Version="10.0.10" />
        <None Update="Images\*.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
